[project]
name = "new-pandas-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hypothesis>=6.135.7",
    "pip>=25.1.1",
    "universal-pathlib>=0.2.6",
    "wat>=0.6.0",
    "whenever>=0.8.0",
]
